Namespace(biom_table='/mnt/home/djin/ceph/snakemake/data/Dan2020ASD_rl150/Dan2020ASD.biom', chains=4, control_group='Control', groups='Status', metadata_file='/mnt/home/djin/ceph/snakemake/data/Dan2020ASD_rl150/sample_metadata_JM.txt', monte_carlo_samples=1000, output_inference='/mnt/home/djin/ceph/snakemake/data/Dan2020ASD_rl150/Dan2020ASD.nc', processes=1)
Traceback (most recent call last):
  File "/mnt/home/djin/miniconda3/envs/birdman3.8/lib/python3.8/site-packages/sklearn/utils/_encode.py", line 224, in _encode
    return _map_to_integer(values, uniques)
  File "/mnt/home/djin/miniconda3/envs/birdman3.8/lib/python3.8/site-packages/sklearn/utils/_encode.py", line 164, in _map_to_integer
    return np.array([table[v] for v in values])
  File "/mnt/home/djin/miniconda3/envs/birdman3.8/lib/python3.8/site-packages/sklearn/utils/_encode.py", line 164, in <listcomp>
    return np.array([table[v] for v in values])
  File "/mnt/home/djin/miniconda3/envs/birdman3.8/lib/python3.8/site-packages/sklearn/utils/_encode.py", line 158, in __missing__
    raise KeyError(key)
KeyError: 'Healthy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "disease_parallel.py", line 46, in <module>
    DiseaseSingle(table, metadata=metadata, feature_id=table.ids(axis='observation')[0],
  File "/mnt/ceph/users/djin/git/q2-differential/q2_differential/_model.py", line 90, in __init__
    reference_cat = disease_encoder.transform([reference])
  File "/mnt/home/djin/miniconda3/envs/birdman3.8/lib/python3.8/site-packages/sklearn/preprocessing/_label.py", line 138, in transform
    return _encode(y, uniques=self.classes_)
  File "/mnt/home/djin/miniconda3/envs/birdman3.8/lib/python3.8/site-packages/sklearn/utils/_encode.py", line 226, in _encode
    raise ValueError(f"y contains previously unseen labels: {str(e)}")
ValueError: y contains previously unseen labels: 'Healthy'
deleting tmpfiles dir: /tmp/tmpxq31llun
done
